version: '3.8'

services:
  db:
    image: postgres:15
    container_name: plastic_waste_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plastic_waste_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql

volumes:
  postgres_data:
