use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use utoipa::ToSchema;

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct Product {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub material_type: Option<String>,
    pub weight_grams: i32,
    pub qr_code_data: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct NewProduct {
    pub company_id: Uuid,
    pub name: String,
    pub material_type: Option<String>,
    pub weight_grams: i32,
    // QR code data will be generated by the system
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdateProduct {
    pub name: Option<String>,
    pub material_type: Option<String>,
    pub weight_grams: Option<i32>,
}
